---
- name: Check if Docker is already present.
  command: which docker
  failed_when: false
  changed_when: false
  check_mode: false
  register: docker_command_result

- name: Download Docker install convenience script.
  get_url:
    url: https://get.docker.com/
    dest: /tmp/get-docker.sh
    mode: 0775
  when: docker_command_result.rc == 1

- name: Run Docker install convenience script.
  command: /tmp/get-docker.sh
  environment:
    CHANNEL: stable
  when: docker_command_result.rc == 1

- name: Make sure Docker CE is the version specified.
  apt:
    name: "docker-ce={{ docker_version }}*"
    state: present
    force: true

- name: Ensure Docker is started.
  service:
    name: docker
    state: started
    enabled: true

- name: Install Docker Compose using Pip.
  pip:
    name: docker-compose
    state: present
    executable: "{{ docker_pip_executable }}"
  when: docker_install_compose | bool

- name: "Create Docker network {{ docker_network }}"
  community.docker.docker_network:
    name: "{{ docker_network }}"
  tags:
    - docker_network

- name: "Create Docker basedir unencrypted {{ docker_non_encrypted_basedir }}"
  file:
    path: "{{ docker_encrypted_basedir }}"
    state: directory
    mode: 0755
    owner: "{{ new_user_PUID | default('0') }}"
    group: "{{ new_user_PGID | default('0') }}"
  when: docker_non_encrypted_basedir is defined 
